name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  check:
    uses: ./.github/workflows/ci.yaml

  binaries:
    needs: check
    uses: ./.github/workflows/build-release.yaml
    with:
      ref: ${{ github.ref }}
